# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 696)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../.designer/backup/imgs/128x128/ipt_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.id_amostra = QtWidgets.QGroupBox(self.tab)
        self.id_amostra.setObjectName("id_amostra")
        self.formLayout_2 = QtWidgets.QFormLayout(self.id_amostra)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblDescricao = QtWidgets.QLabel(self.id_amostra)
        self.lblDescricao.setObjectName("lblDescricao")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblDescricao)
        self.txtFabricante = QtWidgets.QLineEdit(self.id_amostra)
        self.txtFabricante.setMaxLength(256)
        self.txtFabricante.setObjectName("txtFabricante")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtFabricante)
        self.label_9 = QtWidgets.QLabel(self.id_amostra)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtModelo = QtWidgets.QLineEdit(self.id_amostra)
        self.txtModelo.setMaxLength(256)
        self.txtModelo.setObjectName("txtModelo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtModelo)
        self.lblTipo = QtWidgets.QLabel(self.id_amostra)
        self.lblTipo.setObjectName("lblTipo")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblTipo)
        self.cbTipo = QtWidgets.QComboBox(self.id_amostra)
        self.cbTipo.setMaxCount(10)
        self.cbTipo.setObjectName("cbTipo")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbTipo)
        self.label_8 = QtWidgets.QLabel(self.id_amostra)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sb_tempNominal = QtWidgets.QDoubleSpinBox(self.id_amostra)
        self.sb_tempNominal.setProperty("showGroupSeparator", False)
        self.sb_tempNominal.setDecimals(1)
        self.sb_tempNominal.setMaximum(500.0)
        self.sb_tempNominal.setProperty("value", 58.0)
        self.sb_tempNominal.setObjectName("sb_tempNominal")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sb_tempNominal)
        self.label_10 = QtWidgets.QLabel(self.id_amostra)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cbFaixaTemp = QtWidgets.QComboBox(self.id_amostra)
        self.cbFaixaTemp.setObjectName("cbFaixaTemp")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.cbFaixaTemp.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbFaixaTemp)
        self.label_11 = QtWidgets.QLabel(self.id_amostra)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cbLetraCod = QtWidgets.QComboBox(self.id_amostra)
        self.cbLetraCod.setObjectName("cbLetraCod")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.cbLetraCod.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbLetraCod)
        self.lblCores = QtWidgets.QLabel(self.id_amostra)
        self.lblCores.setObjectName("lblCores")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblCores)
        self.cbCores = QtWidgets.QComboBox(self.id_amostra)
        self.cbCores.setObjectName("cbCores")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.cbCores.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cbCores)
        self.label_24 = QtWidgets.QLabel(self.id_amostra)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.txtObservacoes = QtWidgets.QPlainTextEdit(self.id_amostra)
        self.txtObservacoes.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txtObservacoes.setObjectName("txtObservacoes")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtObservacoes)
        self.gridLayout_7.addWidget(self.id_amostra, 1, 0, 1, 1)
        self.id_equips = QtWidgets.QGroupBox(self.tab)
        self.id_equips.setObjectName("id_equips")
        self.formLayout_3 = QtWidgets.QFormLayout(self.id_equips)
        self.formLayout_3.setObjectName("formLayout_3")
        self.tCnico2Label_2 = QtWidgets.QLabel(self.id_equips)
        self.tCnico2Label_2.setObjectName("tCnico2Label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tCnico2Label_2)
        self.cbTermohigrometro = QtWidgets.QComboBox(self.id_equips)
        self.cbTermohigrometro.setObjectName("cbTermohigrometro")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbTermohigrometro)
        self.label_7 = QtWidgets.QLabel(self.id_equips)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cbBanhoOleo = QtWidgets.QComboBox(self.id_equips)
        self.cbBanhoOleo.setObjectName("cbBanhoOleo")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbBanhoOleo)
        self.gridLayout_7.addWidget(self.id_equips, 2, 0, 1, 1)
        self.id_ensaio = QtWidgets.QGroupBox(self.tab)
        self.id_ensaio.setObjectName("id_ensaio")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.id_ensaio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.lblCliente = QtWidgets.QLabel(self.id_ensaio)
        self.lblCliente.setObjectName("lblCliente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCliente)
        self.txtCliente = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtCliente.setMaxLength(256)
        self.txtCliente.setFrame(True)
        self.txtCliente.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txtCliente.setClearButtonEnabled(False)
        self.txtCliente.setObjectName("txtCliente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCliente)
        self.txtOCP = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtOCP.setText("")
        self.txtOCP.setMaxLength(256)
        self.txtOCP.setObjectName("txtOCP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtOCP)
        self.txtOrcamento = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtOrcamento.setText("")
        self.txtOrcamento.setMaxLength(256)
        self.txtOrcamento.setObjectName("txtOrcamento")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtOrcamento)
        self.txtItem = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtItem.setText("")
        self.txtItem.setMaxLength(256)
        self.txtItem.setObjectName("txtItem")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtItem)
        self.lblOCP = QtWidgets.QLabel(self.id_ensaio)
        self.lblOCP.setObjectName("lblOCP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblOCP)
        self.lblOrcamento = QtWidgets.QLabel(self.id_ensaio)
        self.lblOrcamento.setObjectName("lblOrcamento")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblOrcamento)
        self.lblItem = QtWidgets.QLabel(self.id_ensaio)
        self.lblItem.setObjectName("lblItem")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblItem)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblData = QtWidgets.QLabel(self.id_ensaio)
        self.lblData.setObjectName("lblData")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblData)
        self.dateData = QtWidgets.QDateEdit(self.id_ensaio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateData.sizePolicy().hasHeightForWidth())
        self.dateData.setSizePolicy(sizePolicy)
        self.dateData.setObjectName("dateData")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateData)
        self.lblTec1 = QtWidgets.QLabel(self.id_ensaio)
        self.lblTec1.setObjectName("lblTec1")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblTec1)
        self.lblTec2 = QtWidgets.QLabel(self.id_ensaio)
        self.lblTec2.setObjectName("lblTec2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblTec2)
        self.txtTec1 = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtTec1.setMaxLength(256)
        self.txtTec1.setObjectName("txtTec1")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtTec1)
        self.txtTec2 = QtWidgets.QLineEdit(self.id_ensaio)
        self.txtTec2.setMaxLength(256)
        self.txtTec2.setObjectName("txtTec2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtTec2)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout_7.addWidget(self.id_ensaio, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.sb_numAmostras = QtWidgets.QSpinBox(self.groupBox)
        self.sb_numAmostras.setMaximum(50)
        self.sb_numAmostras.setProperty("value", 10)
        self.sb_numAmostras.setObjectName("sb_numAmostras")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_numAmostras)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.sb_qntLinhas = QtWidgets.QSpinBox(self.groupBox)
        self.sb_qntLinhas.setMinimum(1)
        self.sb_qntLinhas.setMaximum(10)
        self.sb_qntLinhas.setProperty("value", 2)
        self.sb_qntLinhas.setObjectName("sb_qntLinhas")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_qntLinhas)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.sb_qntCols = QtWidgets.QSpinBox(self.groupBox)
        self.sb_qntCols.setMinimum(1)
        self.sb_qntCols.setMaximum(10)
        self.sb_qntCols.setProperty("value", 5)
        self.sb_qntCols.setObjectName("sb_qntCols")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sb_qntCols)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_6.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.btn_Visualizar = QtWidgets.QPushButton(self.groupBox)
        self.btn_Visualizar.setObjectName("btn_Visualizar")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_Visualizar)
        self.verticalLayout_5.addLayout(self.formLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.layoutPreview = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutPreview.sizePolicy().hasHeightForWidth())
        self.layoutPreview.setSizePolicy(sizePolicy)
        self.layoutPreview.setMinimumSize(QtCore.QSize(0, 0))
        self.layoutPreview.setMaximumSize(QtCore.QSize(10000, 500))
        self.layoutPreview.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.layoutPreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layoutPreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layoutPreview.setObjectName("layoutPreview")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutPreview)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.previewArea = QtWidgets.QWidget(self.layoutPreview)
        self.previewArea.setObjectName("previewArea")
        self.verticalLayout_6.addWidget(self.previewArea)
        self.verticalLayout_5.addWidget(self.layoutPreview)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(3, 2)
        self.gridLayout_7.addWidget(self.groupBox, 0, 1, 3, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnSaveEnsaio = QtWidgets.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../.designer/backup/imgs/16x16/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveEnsaio.setIcon(icon1)
        self.btnSaveEnsaio.setAutoDefault(False)
        self.btnSaveEnsaio.setObjectName("btnSaveEnsaio")
        self.horizontalLayout_4.addWidget(self.btnSaveEnsaio)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.txtPastaEnsaio = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtPastaEnsaio.setReadOnly(True)
        self.txtPastaEnsaio.setObjectName("txtPastaEnsaio")
        self.horizontalLayout_8.addWidget(self.txtPastaEnsaio)
        self.btnBuscarPasta = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBuscarPasta.setObjectName("btnBuscarPasta")
        self.horizontalLayout_8.addWidget(self.btnBuscarPasta)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.gridLayout_7.setRowStretch(0, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnsFrame = QtWidgets.QFrame(self.tab_3)
        self.btnsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnsFrame.setObjectName("btnsFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.btnsFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout.addWidget(self.btnsFrame, 6, 0, 1, 3)
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(140, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblHeadTaxa = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblHeadTaxa.setFont(font)
        self.lblHeadTaxa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeadTaxa.setObjectName("lblHeadTaxa")
        self.gridLayout_4.addWidget(self.lblHeadTaxa, 0, 0, 1, 4)
        self.lblTaxa = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTaxa.setFont(font)
        self.lblTaxa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTaxa.setObjectName("lblTaxa")
        self.gridLayout_4.addWidget(self.lblTaxa, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_7.setObjectName("formLayout_7")
        self.lblHeadTempo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblHeadTempo.setFont(font)
        self.lblHeadTempo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeadTempo.setObjectName("lblHeadTempo")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblHeadTempo)
        self.lblTempo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTempo.setFont(font)
        self.lblTempo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTempo.setObjectName("lblTempo")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblTempo)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lblHora = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHora.setFont(font)
        self.lblHora.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHora.setObjectName("lblHora")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblHora)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(20, 50, 59, 15))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(140, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblHeadTemp = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblHeadTemp.setFont(font)
        self.lblHeadTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeadTemp.setObjectName("lblHeadTemp")
        self.gridLayout_3.addWidget(self.lblHeadTemp, 0, 0, 1, 4)
        self.lblTemp = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTemp.setFont(font)
        self.lblTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTemp.setObjectName("lblTemp")
        self.gridLayout_3.addWidget(self.lblTemp, 1, 0, 1, 4)
        self.lblTempMax = QtWidgets.QLabel(self.frame_2)
        self.lblTempMax.setObjectName("lblTempMax")
        self.gridLayout_3.addWidget(self.lblTempMax, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 1, 1, 1)
        self.lblTempMin = QtWidgets.QLabel(self.frame_2)
        self.lblTempMin.setObjectName("lblTempMin")
        self.gridLayout_3.addWidget(self.lblTempMin, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(6, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 3, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_startEnsaio = QtWidgets.QPushButton(self.tab_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../.designer/backup/imgs/16x16/dark/p-right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_startEnsaio.setIcon(icon2)
        self.btn_startEnsaio.setObjectName("btn_startEnsaio")
        self.horizontalLayout_3.addWidget(self.btn_startEnsaio)
        self.btnRegistrar = QtWidgets.QPushButton(self.tab_3)
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.horizontalLayout_3.addWidget(self.btnRegistrar)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.ensaioFrame = QtWidgets.QFrame(self.tab_3)
        self.ensaioFrame.setStyleSheet("")
        self.ensaioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ensaioFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ensaioFrame.setObjectName("ensaioFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ensaioFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotWidget = PlotWidget(self.ensaioFrame)
        self.plotWidget.setStyleSheet("")
        self.plotWidget.setObjectName("plotWidget")
        self.verticalLayout.addWidget(self.plotWidget)
        self.verticalLayout.setStretch(0, 2)
        self.gridLayout_5.addWidget(self.ensaioFrame, 0, 1, 1, 1)
        self.tableRegistros = QtWidgets.QTableWidget(self.tab_3)
        self.tableRegistros.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableRegistros.setAlternatingRowColors(False)
        self.tableRegistros.setObjectName("tableRegistros")
        self.tableRegistros.setColumnCount(6)
        self.tableRegistros.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRegistros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRegistros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRegistros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRegistros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableRegistros.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableRegistros.setHorizontalHeaderItem(5, item)
        self.tableRegistros.horizontalHeader().setStretchLastSection(True)
        self.tableRegistros.verticalHeader().setVisible(False)
        self.tableRegistros.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableRegistros, 2, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setRowStretch(0, 6)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.serial_configs = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_configs.sizePolicy().hasHeightForWidth())
        self.serial_configs.setSizePolicy(sizePolicy)
        self.serial_configs.setObjectName("serial_configs")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.serial_configs)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.serial_configs)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_port = QtWidgets.QComboBox(self.serial_configs)
        self.cb_port.setObjectName("cb_port")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_port)
        self.label_13 = QtWidgets.QLabel(self.serial_configs)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_baud = QtWidgets.QComboBox(self.serial_configs)
        self.cb_baud.setObjectName("cb_baud")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_baud)
        self.label_14 = QtWidgets.QLabel(self.serial_configs)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cb_datasize = QtWidgets.QComboBox(self.serial_configs)
        self.cb_datasize.setObjectName("cb_datasize")
        self.cb_datasize.addItem("")
        self.cb_datasize.addItem("")
        self.cb_datasize.addItem("")
        self.cb_datasize.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_datasize)
        self.label_15 = QtWidgets.QLabel(self.serial_configs)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cb_parity = QtWidgets.QComboBox(self.serial_configs)
        self.cb_parity.setObjectName("cb_parity")
        self.cb_parity.addItem("")
        self.cb_parity.addItem("")
        self.cb_parity.addItem("")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_parity)
        self.label_16 = QtWidgets.QLabel(self.serial_configs)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cb_stopbits = QtWidgets.QComboBox(self.serial_configs)
        self.cb_stopbits.setObjectName("cb_stopbits")
        self.cb_stopbits.addItem("")
        self.cb_stopbits.addItem("")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_stopbits)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.horizontalLayout_5.setStretch(0, 2)
        self.gridLayout_2.addWidget(self.serial_configs, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action9600 = QtWidgets.QAction(MainWindow)
        self.action9600.setCheckable(True)
        self.action9600.setObjectName("action9600")
        self.action115200 = QtWidgets.QAction(MainWindow)
        self.action115200.setObjectName("action115200")
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtCliente, self.txtOCP)
        MainWindow.setTabOrder(self.txtOCP, self.txtOrcamento)
        MainWindow.setTabOrder(self.txtOrcamento, self.txtItem)
        MainWindow.setTabOrder(self.txtItem, self.dateData)
        MainWindow.setTabOrder(self.dateData, self.txtTec1)
        MainWindow.setTabOrder(self.txtTec1, self.txtTec2)
        MainWindow.setTabOrder(self.txtTec2, self.txtFabricante)
        MainWindow.setTabOrder(self.txtFabricante, self.txtModelo)
        MainWindow.setTabOrder(self.txtModelo, self.cbTipo)
        MainWindow.setTabOrder(self.cbTipo, self.cbLetraCod)
        MainWindow.setTabOrder(self.cbLetraCod, self.sb_tempNominal)
        MainWindow.setTabOrder(self.sb_tempNominal, self.cbFaixaTemp)
        MainWindow.setTabOrder(self.cbFaixaTemp, self.cbCores)
        MainWindow.setTabOrder(self.cbCores, self.txtObservacoes)
        MainWindow.setTabOrder(self.txtObservacoes, self.cbTermohigrometro)
        MainWindow.setTabOrder(self.cbTermohigrometro, self.cbBanhoOleo)
        MainWindow.setTabOrder(self.cbBanhoOleo, self.btnBuscarPasta)
        MainWindow.setTabOrder(self.btnBuscarPasta, self.sb_numAmostras)
        MainWindow.setTabOrder(self.sb_numAmostras, self.sb_qntLinhas)
        MainWindow.setTabOrder(self.sb_qntLinhas, self.sb_qntCols)
        MainWindow.setTabOrder(self.sb_qntCols, self.btn_Visualizar)
        MainWindow.setTabOrder(self.btn_Visualizar, self.btnSaveEnsaio)
        MainWindow.setTabOrder(self.btnSaveEnsaio, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.txtPastaEnsaio)
        MainWindow.setTabOrder(self.txtPastaEnsaio, self.btn_startEnsaio)
        MainWindow.setTabOrder(self.btn_startEnsaio, self.btnRegistrar)
        MainWindow.setTabOrder(self.btnRegistrar, self.tableRegistros)
        MainWindow.setTabOrder(self.tableRegistros, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.cb_port)
        MainWindow.setTabOrder(self.cb_port, self.cb_baud)
        MainWindow.setTabOrder(self.cb_baud, self.cb_datasize)
        MainWindow.setTabOrder(self.cb_datasize, self.cb_parity)
        MainWindow.setTabOrder(self.cb_parity, self.cb_stopbits)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Teste de Temperatura para Sprinklers"))
        self.id_amostra.setTitle(_translate("MainWindow", "Identificação da Amostra:"))
        self.lblDescricao.setText(_translate("MainWindow", "Fabricante:"))
        self.label_9.setText(_translate("MainWindow", "Modelo:"))
        self.lblTipo.setText(_translate("MainWindow", "Tipo elemento termossensível:"))
        self.cbTipo.setItemText(0, _translate("MainWindow", "Liga fusível"))
        self.cbTipo.setItemText(1, _translate("MainWindow", "Ampola de vidro"))
        self.label_8.setText(_translate("MainWindow", "Temp. de operação declarada (°C):"))
        self.label_10.setText(_translate("MainWindow", "Faixa de temp. nominal  de operação (°C):"))
        self.cbFaixaTemp.setItemText(0, _translate("MainWindow", "57 a 77"))
        self.cbFaixaTemp.setItemText(1, _translate("MainWindow", "79 a 107"))
        self.cbFaixaTemp.setItemText(2, _translate("MainWindow", "121 a 149"))
        self.cbFaixaTemp.setItemText(3, _translate("MainWindow", "163 a 191"))
        self.cbFaixaTemp.setItemText(4, _translate("MainWindow", "204 a 246"))
        self.cbFaixaTemp.setItemText(5, _translate("MainWindow", "260 a 302"))
        self.cbFaixaTemp.setItemText(6, _translate("MainWindow", "320 a 343"))
        self.cbFaixaTemp.setItemText(7, _translate("MainWindow", "Outro"))
        self.label_11.setText(_translate("MainWindow", "Letra código:"))
        self.cbLetraCod.setItemText(0, _translate("MainWindow", "EC – chuveiro de cobertura estendida"))
        self.cbLetraCod.setItemText(1, _translate("MainWindow", "QR – chuveiro de resposta rápida"))
        self.cbLetraCod.setItemText(2, _translate("MainWindow", "SU ou SSU ou F – chuveiro em pé tipo spray"))
        self.cbLetraCod.setItemText(3, _translate("MainWindow", "SP ou SSP ou H – chuveiro pendente tipo spray"))
        self.cbLetraCod.setItemText(4, _translate("MainWindow", "WU – chuveiro lateral pendente"))
        self.cbLetraCod.setItemText(5, _translate("MainWindow", "WUP – chuveiro lateral em pé"))
        self.cbLetraCod.setItemText(6, _translate("MainWindow", "WH ou LH – chuveiro lateral horizontal"))
        self.cbLetraCod.setItemText(7, _translate("MainWindow", "ESFR – chuveiro de supressão imediata e resposta rápida"))
        self.cbLetraCod.setItemText(8, _translate("MainWindow", "Não aplicável"))
        self.lblCores.setText(_translate("MainWindow", "Cor dos braços:"))
        self.cbCores.setItemText(0, _translate("MainWindow", "Incolor ou preta"))
        self.cbCores.setItemText(1, _translate("MainWindow", "Branca"))
        self.cbCores.setItemText(2, _translate("MainWindow", "Azul"))
        self.cbCores.setItemText(3, _translate("MainWindow", "Vermelha"))
        self.cbCores.setItemText(4, _translate("MainWindow", "Verde"))
        self.cbCores.setItemText(5, _translate("MainWindow", "Laranja"))
        self.cbCores.setItemText(6, _translate("MainWindow", "Outro"))
        self.label_24.setText(_translate("MainWindow", "Observações:"))
        self.id_equips.setTitle(_translate("MainWindow", "Equipamentos:"))
        self.tCnico2Label_2.setText(_translate("MainWindow", "Termohigrômetro:"))
        self.label_7.setText(_translate("MainWindow", "Banho de óleo:"))
        self.id_ensaio.setTitle(_translate("MainWindow", "Identificação do Ensaio:"))
        self.lblCliente.setText(_translate("MainWindow", "Cliente:"))
        self.lblOCP.setText(_translate("MainWindow", "OCP:"))
        self.lblOrcamento.setText(_translate("MainWindow", "Orçamento N°:"))
        self.lblItem.setText(_translate("MainWindow", "Item N°:"))
        self.lblData.setText(_translate("MainWindow", "Data:"))
        self.lblTec1.setText(_translate("MainWindow", "Técnico 1:"))
        self.lblTec2.setText(_translate("MainWindow", "Técnico 2:"))
        self.groupBox.setTitle(_translate("MainWindow", "Ensaio:"))
        self.label_18.setText(_translate("MainWindow", "Quantidade de linhas:"))
        self.label_19.setText(_translate("MainWindow", "Quantidade de colunas:"))
        self.label_17.setText(_translate("MainWindow", "Número de amostras acomodadas no banho:"))
        self.btn_Visualizar.setText(_translate("MainWindow", "Visualizar"))
        self.label_20.setText(_translate("MainWindow", "Mapa de acomodação das amostras no banho:"))
        self.layoutPreview.setProperty("name", _translate("MainWindow", "frame"))
        self.btnSaveEnsaio.setText(_translate("MainWindow", "Salvar Dados do Ensaio"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Diretório do Ensaio:"))
        self.label_26.setText(_translate("MainWindow", "Caminho:"))
        self.btnBuscarPasta.setText(_translate("MainWindow", "Explorar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dados do Ensaio"))
        self.btnsFrame.setProperty("name", _translate("MainWindow", "frame"))
        self.frame_3.setProperty("name", _translate("MainWindow", "frame"))
        self.lblHeadTaxa.setText(_translate("MainWindow", "Taxa de Elevação\n"
"(°C/min)"))
        self.lblTaxa.setText(_translate("MainWindow", "0.6"))
        self.label_2.setText(_translate("MainWindow", "max:"))
        self.label_5.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "min:"))
        self.label_6.setText(_translate("MainWindow", "0.0"))
        self.frame.setProperty("name", _translate("MainWindow", "frame"))
        self.lblHeadTempo.setText(_translate("MainWindow", "Tempo decorrido:"))
        self.lblTempo.setText(_translate("MainWindow", "00:00:00"))
        self.label_21.setText(_translate("MainWindow", "Hora início:"))
        self.lblHora.setText(_translate("MainWindow", "00:00:00"))
        self.frame_2.setProperty("name", _translate("MainWindow", "frame"))
        self.lblHeadTemp.setText(_translate("MainWindow", "Temperatura\n"
"Banho (°C)"))
        self.lblTemp.setText(_translate("MainWindow", "20.00"))
        self.lblTempMax.setText(_translate("MainWindow", "0.0"))
        self.label.setText(_translate("MainWindow", "max:"))
        self.label_3.setText(_translate("MainWindow", "min:"))
        self.lblTempMin.setText(_translate("MainWindow", "0.0"))
        self.label_23.setText(_translate("MainWindow", "Botões de Registro de Rompimento"))
        self.btn_startEnsaio.setText(_translate("MainWindow", " Iniciar"))
        self.btnRegistrar.setText(_translate("MainWindow", "Registrar"))
        self.ensaioFrame.setProperty("name", _translate("MainWindow", "frame"))
        item = self.tableRegistros.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item #"))
        item = self.tableRegistros.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableRegistros.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Temp (°C)"))
        item = self.tableRegistros.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Rompimento"))
        item = self.tableRegistros.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Resultado"))
        item = self.tableRegistros.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Observações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Ensaio"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Arquivos de Log"))
        self.label_25.setText(_translate("MainWindow", "Pasta destino:"))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.serial_configs.setTitle(_translate("MainWindow", "Comunicação Serial"))
        self.label_12.setText(_translate("MainWindow", "Porta:"))
        self.label_13.setText(_translate("MainWindow", "Baudrate:"))
        self.cb_baud.setItemText(0, _translate("MainWindow", "1200"))
        self.cb_baud.setItemText(1, _translate("MainWindow", "1600"))
        self.cb_baud.setItemText(2, _translate("MainWindow", "2400"))
        self.cb_baud.setItemText(3, _translate("MainWindow", "4800"))
        self.cb_baud.setItemText(4, _translate("MainWindow", "9600"))
        self.cb_baud.setItemText(5, _translate("MainWindow", "19200"))
        self.cb_baud.setItemText(6, _translate("MainWindow", "38400"))
        self.cb_baud.setItemText(7, _translate("MainWindow", "57600"))
        self.cb_baud.setItemText(8, _translate("MainWindow", "115200"))
        self.label_14.setText(_translate("MainWindow", "Bits de dado:"))
        self.cb_datasize.setItemText(0, _translate("MainWindow", "5"))
        self.cb_datasize.setItemText(1, _translate("MainWindow", "6"))
        self.cb_datasize.setItemText(2, _translate("MainWindow", "7"))
        self.cb_datasize.setItemText(3, _translate("MainWindow", "8"))
        self.label_15.setText(_translate("MainWindow", "Bit de paridade:"))
        self.cb_parity.setItemText(0, _translate("MainWindow", "Paridade ímpar"))
        self.cb_parity.setItemText(1, _translate("MainWindow", "Paridade par"))
        self.cb_parity.setItemText(2, _translate("MainWindow", "Nenhum"))
        self.label_16.setText(_translate("MainWindow", "Stop bits:"))
        self.cb_stopbits.setItemText(0, _translate("MainWindow", "1"))
        self.cb_stopbits.setItemText(1, _translate("MainWindow", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Configurações"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.action9600.setText(_translate("MainWindow", "9600"))
        self.action115200.setText(_translate("MainWindow", "115200"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

